"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.vgg import VGG11
from kimm._src.models.vgg import VGG13
from kimm._src.models.vgg import VGG16
from kimm._src.models.vgg import VGG19
