"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.mobilenet_v2 import MobileNetV2W050
from kimm._src.models.mobilenet_v2 import MobileNetV2W100
from kimm._src.models.mobilenet_v2 import MobileNetV2W110
from kimm._src.models.mobilenet_v2 import MobileNetV2W120
from kimm._src.models.mobilenet_v2 import MobileNetV2W140
