"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.convmixer import ConvMixer736D32
from kimm._src.models.convmixer import ConvMixer1024D20
from kimm._src.models.convmixer import ConvMixer1536D20
