"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.regnet import RegNetX002
from kimm._src.models.regnet import RegNetX004
from kimm._src.models.regnet import RegNetX006
from kimm._src.models.regnet import RegNetX008
from kimm._src.models.regnet import RegNetX016
from kimm._src.models.regnet import RegNetX032
from kimm._src.models.regnet import RegNetX040
from kimm._src.models.regnet import RegNetX064
from kimm._src.models.regnet import RegNetX080
from kimm._src.models.regnet import RegNetX120
from kimm._src.models.regnet import RegNetX160
from kimm._src.models.regnet import RegNetX320
from kimm._src.models.regnet import RegNetY002
from kimm._src.models.regnet import RegNetY004
from kimm._src.models.regnet import RegNetY006
from kimm._src.models.regnet import RegNetY008
from kimm._src.models.regnet import RegNetY016
from kimm._src.models.regnet import RegNetY032
from kimm._src.models.regnet import RegNetY040
from kimm._src.models.regnet import RegNetY064
from kimm._src.models.regnet import RegNetY080
from kimm._src.models.regnet import RegNetY120
from kimm._src.models.regnet import RegNetY160
from kimm._src.models.regnet import RegNetY320
