"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.resnet import ResNet18
from kimm._src.models.resnet import ResNet34
from kimm._src.models.resnet import ResNet50
from kimm._src.models.resnet import ResNet101
from kimm._src.models.resnet import ResNet152
