"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.repvgg import RepVGGA0
from kimm._src.models.repvgg import RepVGGA1
from kimm._src.models.repvgg import RepVGGA2
from kimm._src.models.repvgg import RepVGGB0
from kimm._src.models.repvgg import RepVGGB1
from kimm._src.models.repvgg import RepVGGB2
from kimm._src.models.repvgg import RepVGGB3
