"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from kimm._src.models.hgnet import HGNetBase
from kimm._src.models.hgnet import HGNetSmall
from kimm._src.models.hgnet import HGNetTiny
from kimm._src.models.hgnet import HGNetV2B0
from kimm._src.models.hgnet import HGNetV2B1
from kimm._src.models.hgnet import HGNetV2B2
from kimm._src.models.hgnet import HGNetV2B3
from kimm._src.models.hgnet import HGNetV2B4
from kimm._src.models.hgnet import HGNetV2B5
from kimm._src.models.hgnet import HGNetV2B6
